### ISSUE TITLE
Don't update/install gecko.driver

### ISSUE THREAD

**Issue by bmsdave** [angular/webdriver-manager#178]
Hi! help me, plz.
if I run `webdriver-manager update` - I download gecko driver. Сan I don't download gecko driver?
and where can I find complete documentation webdriver-manager?

**Comment by cnishina** [comment]
Yes you do not have to download gecko driver.
```
webdriver-manager update --gecko false
```

All these flags are in the help:
```
webdriver-manager help
```
or for specific commands:
```
webdriver-manager update help
```

**Comment by djom20** [comment]
Hi, 

Actually I'm using this flag `webdriver-manager update --gecko false` but now I facing another issue since the webdriver says: `Ignoring uncaught error WebDriverError: unknown error: cannot find Chrome binary` but I don't know why.

![image](https://user-images.githubusercontent.com/1834808/55245184-a3a58980-5210-11e9-886f-801e894caab0.png)

**Comment by cnishina** [comment]
So.... maybe open up a new bug? Visibility is tough when the bug is closed and 2+ years old.

My guess is that you have defined the Chrome binary yourself and the test cannot find it. I'm also not sure what version of node, Chrome, Protractor and webdriver-manager you are using. What is the test that causes this error? Is it related to an onPrepare plugin or beforeLaunch plugin? The more you can provide the better I can triage this if this is a bug with the framework or point you in the right direction to how to fix it.
