### ISSUE TITLE
Standalone server 3 shutdown does not work

### ISSUE THREAD

**Issue by cnishina** [angular/webdriver-manager#199]
Shutdown command with `/selenium-server/driver/?cmd=shutDownSeleniumServer` is [no longer supported in selenium standalone 3](https://github.com/SeleniumHQ/selenium/issues/2852#issuecomment-250841027) and will be an issue here: https://github.com/angular/webdriver-manager/blob/master/lib/cmds/shutdown.ts#L35

**Comment by rochejul** [comment]
Indeed, and it impacts my plugin: https://github.com/rochejul/gulp-angular-protractor/issues/44

Many thanks for your feedback

**Comment by lufecir** [comment]
This also breaks our CI build after upgrading to Protractor 5 (and selenium 3.x).
There seems to be quite some discussion around this on the selenium threads, and [this comment](https://github.com/SeleniumHQ/selenium/issues/2852#issuecomment-268324091) suggests that by starting the selenium server differently would allow to execute a shutdown command like we used to have available with standalone server 2.x.
Are there any plans to support this way or starting the selenium webdriver as a node with LifeCycleServlet instead of a standalone server?

For now I have been able to work around this by using a pretty ugly windows command line script (added below to help anyone running into a similar problem), but I would really prefer to have a cleaner way to stop the selenium webdriver.

`cmd /V /C "echo off && set "killed=0" && (for /F "tokens=5" %a in ('netstat -ano ^| findstr ":4444"') do if not %a == 0 if not !killed! == 1 (taskkill /F /PID %a && set "killed=1")) || echo No webdriver process found"'`

Some explanation on the script (which has to be a oneliner for our CI build scripts):
* The body of the script is the 'netstat -ano ^| findstr ":4444"' which lists all processes connected to port 4444 (the default port of the Selenium webdriver server)
* The for loop then loops through this and stores the 5th token (PID) in the variable %a
* For each process found a 'taskkill /F /PID %a' is then executed to kill it
* But the list of processes contains 2 entries for the webdriver process and lots of entries on PID 0 for connections (from the Protractor tests) that have been released by the tests but are still kept by the system for a few minutes. 
So in order to kill only a single process, we need the checks 'NOT %a == 0' and 'NOT !killed! == 1'
* Finally the '|| echo No webdriver process found' ensures the script exits nicely in case no webdriver process is active (anymore)
* The 'cmd /V' and exclamation mark reference to the 'killed' variable are needed because we need delayed expansion in the for loop (see https://ss64.com/nt/delayedexpansion.html)

**Comment by elhigu** [comment]
@lufecir I made quick implementation to start the standalone server with lifecycle servlet and changed shutdown paths accordingly #274

**Comment by lufecir** [comment]
@elhigu That is great. Looking forward to getting rid of that script hack I am using now. 
Thanks.

**Comment by cnishina** [comment]
And this works in version 13: `webdriver-manager start --detach` and `webdriver-manager shutdown` works. Closing this issue.

**Comment by wunaidage** [comment]
> And this works in version 13: `webdriver-manager start --detach` and `webdriver-manager shutdown` works. Closing this issue.

excuse me, where can I find version 13?
