### ISSUE TITLE
Something send wrong script to select Phantom for Selenium

### ISSUE THREAD

**Issue by michaeljota** [angular/webdriver-manager#202]
OS: Windows 10 AU
node: 6.9.4
npm: 3.10.10

Package:
```json
{
  "name": "intern-tutorial",
  "version": "3.0.0",
  "description": "Intern tutorial. Learn how to use Intern by following this tutorial!",
  "repository": {
    "type": "git",
    "url": "https://github.com/theintern/intern-tutorial.git"
  },
  "license": "BSD-3-Clause",
  "bugs": "https://github.com/theintern/intern-tutorial/issues",
  "homepage": "http://theintern.io/",
  "scripts": {
    "intern": "intern-client",
    "intern-runner": "intern-runner",
    "phantomjs": "phantomjs",
    "webdriver-manager": "webdriver-manager"
  },
  "devDependencies": {
    "intern": "^3.4.2",
    "phantomjs-prebuilt": "^2.1.14",
    "webdriver-manager": "^11.1.1"
  }
}
```

Issue:
I'm trying to run the [`intern`](https://github.com/theintern/intern) tutorial, but instead of doing it in StackBrowser, I wanted a local headless setup, with Phantom. I'm running Selenium through `webdriver-manager`. When I run `intern-runner` selecting Phantom, the server running with `webdriver-manager` tries to run `~\node_modules\.bin\phantomjs`, but that's the *nix version of the script. If I rename (or delete) that file, then it fallback to `~\node_modules\.bin\phantomjs.cmd`, the Windows version. 

I reported this in theintern/intern#716, but someone pointed this might be an issue with `webdriver-manager`.

**Comment by cnishina** [comment]
I'm not sure how this is a webdriver-manager issue. The command line does not download or start the standalone server with phantomjs. I see that phantomjs and webdriver-manager are dependencies to your project; however, it is unclear what you are sending webdriver-manager to start the standalone server with phantomjs. I do not believe that this is a feature (yet).

Looking over their tutorial, it might be better to start the standalone server with the jar command.

Another thing to try, can you start chrome instead of phantom? Does that work?

**Comment by michaeljota** [comment]
I have not try to launch chrome yet. Sorry.

**Comment by cnishina** [comment]
After reviewing your other issue with `theintern/intern` project, I believe that this is outside of the scope of `webdriver-manager`. Thanks for your issue.
