### ISSUE TITLE
Unit tests all fail when github rate limit is reached

### ISSUE THREAD

**Issue by benjaminapetersen** [angular/webdriver-manager#287]
`npm run test-unit` 

results in this:

![screen shot 2017-11-09 at 4 53 27 pm](https://user-images.githubusercontent.com/280512/32631577-a37913c6-c56e-11e7-89f7-8ee496482e51.png)

**Comment by cnishina** [comment]
That is how github limits reach. I suggest backing off the amount of clean updates you make. Either we need to have some authenticated version where you provide the credentials for github or we drop geckodriver. Please feel free to tell GeckoDriver to host their binaries on something other than just Github.

Since this is not really an issue with webdriver-manager  (and I believe this is documented in another issue already), I am closing this.
