### ISSUE TITLE
not able to run project using npm run e2e command on VM with no internet connectivity

### ISSUE THREAD

**Issue by praveenkmishra** [angular/webdriver-manager#306]
I am trying to execute command webdriver-manager update and I am getting below mention error.
I am on VM where internet connectivity is not available.

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND selenium-release.storage.googleapis.com selenium-release.storage.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

When I run my project in protractor using npm run e2e  I am getting below error
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND chromedriver.storage.googleapis.com chromedriver.storage.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

I am trying to execute command webdriver-manager update and I am getting below mention error.
I am on VM where internet connectivity is not available.

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND selenium-release.storage.googleapis.com selenium-release.storage.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

When I run my project in protractor using npm run e2e  I am getting below error
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND chromedriver.storage.googleapis.com chromedriver.storage.googleapis.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

**Comment by macroking** [comment]
When you do `webdriver-manager` update, the program tries to download the selenium server, chrome driver, and gecko driver. If you don't have an internet connection, it is obvious to fail.

**Comment by everflux** [comment]
It would be great if there would be a way to tell webdriver-manager to just use what is already present instead of updating to the latest versions.
For example an environment variable would work great, that way a separately provided driver could mitigate the offline issue mentioned in this ticket as well as the situation that webdriver-manager updates to a version that is not compatible with the chrome/browser version present on the system, leading to breaking builds.

**Comment by cnishina** [comment]
So we do check the age of the cached file. I think what it is doing is making a HEAD call to see the size of the file and comparing it against the download. If the cache is recent, we could maybe assume that we do not need to make the web call.

We could then check to see if the jar, tar, or zip file exists. If it is a compressed file, we could check to see if there is an uncompressed file. 

If a file is missing, we would then start the download and uncompress the file.

If the files are not completed during a previous update, hopefully there is a reasonable error. Maybe this should be logged in debug that we are usiing files that already exist and will not download them.

**Comment by cnishina** [comment]
Not sure if that made sense. I think this is just an additional check we need to do. If your cache is too old, it will then make a call externally. I could provide an override for it; however, I'm not sure how many users will need this feature. I am leaning against overriding this specific functionality.

**Comment by cnishina** [comment]
Okay we had a discussion about it and being online is a prereq to calling `update`.  @everflux we will support a config file for pinning downloads and also starting the server. Instead of checking the file for the last version downloaded we could refer to the config first. Closing this issue since it is being tracked in #280.
