### ISSUE TITLE
webdriver-manager update-to-actual?

### ISSUE THREAD

**Issue by Antibrumm** [angular/webdriver-manager#322]
Hello
As far as I can tell webdriver-manager update "simply" updates the driver to the latest version.

It would be great if there is a possibility to update the driver to match the actual installed version of the browser.

This is probably not an issue if protractor is installed globally and the webdriver update is launched manually if needed when the browser got updated.

In a local installation (and probably mostly on a development machine) running tests can suddenly start to fail if the browser got updated and we do not include the update command in the post-install script. 

Is there a workaround for that problem or would it make sense to try to update the selenium driver to match the current installed version?

**Comment by cnishina** [comment]
So this is a neat idea. I also thought about that too...

## Some potential problems:

* Parsing a change log to maybe find the version is not trivial. It would be easier if it was in some metadata in the binary or in the release metadata (json or xml files)
* Locating the installed browser on all operating systems and then getting the browser version from command line might be difficult.

## Thoughts about driver versions and CI

Let's say your CI environment has Chrome v67 and we keep downloading ChromeDriver v2.40 as the compatible version. We keep downloading v2.40 and the latest Chrome released is version 75. Would you want to keep downloading v2.40 because the CI environment has not been updated? Would you want to potentially break your CI because you are not on the latest version of a browser / potentially an out of date browser?

**Comment by Antibrumm** [comment]
The problem with identifying each browsers version is indeed not easy to achieve and has the potential to break at any time. I don't know how stable these changelog files and their locations are.

I was thinking to take another approach and get a portable version of chrome during the install phase. This would allow to define exactly which version to download and also use the webdriver update command for a fixed version.

**Comment by cnishina** [comment]
Having a portable chrome version defeats the idea that we should test websites with applications a user would use. However, I think you might want to try this: https://developers.google.com/web/tools/puppeteer/

Hope that helps.

**Comment by cnishina** [comment]
Closing this issue.
