### ISSUE TITLE
alternate_cdn is ignored (discussion)

### ISSUE THREAD

**Issue by CSchulz** [angular/webdriver-manager#325]
V. 12.1.0

Running the command with alternate_cdn tries to download the file via the URL defined in config.json:

```
./node_modules/.bin/webdriver-manager update --gecko=false --standalone=false --alternate_cdn=https://mychromemirror --verbose
https://mychromemirror
ChromeDriver {
  ostype: 'Darwin',
  osarch: 'x64',
  cdn: 'https://mychromemirror',
  configSource:
   ChromeXml {
     ostype: 'Darwin',
     osarch: 'x64',
     out_dir:
      '.../node_modules/protractor/node_modules/webdriver-manager/selenium',
     name: 'chrome',
     xmlUrl: 'https://chromedriver.storage.googleapis.com/' },
  name: 'chromedriver',
  versionDefault: '2.27',
  versionCustom: '2.27' }
[15:40:05] I/downloader - curl -o.../node_modules/webdriver-manager/selenium/chromedriver_2.42.zip https://chromedriver.storage.googleapis.com/2.42/chromedriver_mac64.zip
[15:40:05] I/update - chromedriver: unzipping chromedriver_2.42.zip
[15:40:05] I/update - chromedriver: setting permissions to 0755 for .../node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.42
```

I think the reason is the missing pass through of the alternate cdn to the config file f.e. https://github.com/angular/webdriver-manager/blob/6775421ea9e40db1bf547bcedcb716ba35106a80/lib/binaries/chrome_xml.ts#L9-L11

**Comment by vort3xxx** [comment]
I'm able to point to this guy's alternate cdn and it works for me: https://github.com/JohannesHoppe/webdriver-manager-alternate-cdn

I think the problem is that your cdn is only the chrome stuff & not all the things that need downloaded in the right structure.

**Comment by cnishina** [comment]
Okay. So I have more questions:

* Is this a good idea from a security standpoint to download binaries that someone says is the binary?
* Is there no way to get the regular update to work? Is using a proxy an option? If you can use a proxy, can you try https://github.com/cnishina/webdriver-manager-replacement? I have tested the whole thing to work against a proxy (probably needs documentation). I also want to eventually update this project with this. It still works the same where alternative_cdn does not exist.

Finally is the goal to download files like:

```
webdriver-manager update --url.chrome=http://someurl.to.download.chromedriver.directly -- url.standalone=http://someurl.to.download.seleniumserver.directly
```

I definitely think the flag name should be renamed since it runs a different workflow. Alternative cdn implies that there's an endpoint that has the exact same setup to download a cache of versions and parses the file to find a downloadable version.

Downloading a file by URL might be helpful because of the way webdriver-manager downloads files. This might be important so it can create the file (in the current project this is update-config.json) required to run directConnect or starting Protractor with a local driverProvider.

**Comment by CSchulz** [comment]
I think in a corporate environment you can trust the alternative source for binaries.

Our workaround is downloading the binary manually:

     mkdir -p node_modules/protractor/node_modules/webdriver-manager/selenium
     curl -o node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_${chromeDriverVersion}.zip ${cdnUrl}/${chromeDriverVersion}/chromedriver_linux64.zip
     cd node_modules/protractor/node_modules/webdriver-manager/
     unzip chromedriver_${chromeDriverVersion}.zip
     chmod 755 chromedriver

And setting the chromeDriver binary in the protractor.conf.js.

**Comment by hdeadman** [comment]
The organization I am working at (government) is currently blocking storage.googleapis.com so we are trying to figure out how to work around that. Could these files be packaged into their own NPMs like the selenium-server-standalone-jar NPM? Or could they be downloaded from a site with better content curation (i.e. less likely to be blocked)?

**Comment by cnishina** [comment]
* GitHub rate has been fixed.
* @hdeadman So if you cannot download to storage.googleapis.com, could you get access via proxy? Packaging binaries in npm would be not ideal. I don't think this is probably good practice.

So I guess if you had a box externally that did a proxy forward to storage.googleapis.com, you could download from whatever host name you created?

So instead doing something like: 

```
curl -o /path/to/downloads/chromedriver.xml https://chromedriver.storage.googleapis.com/
```

You could call:

```
curl -o /path/to/downloads/chromedriver.xml https://myrandomurl.com/
```

I guess if this is the specific use case, I could maybe create the basic nginx config for this and provide it when you use an an "alternative_cdn". And all the calls would go to (in this example), myrandomurl.com. When calling GitHub, I'm not sure how this will handle the redirects.

**Comment by cnishina** [comment]
Should also look at #300

**Comment by cnishina** [comment]
Okay after discussion with the team offline, this is not something we will support.

**Comment by hmil** [comment]
May I ask why would you provide the option `--alternate_cdn` if it doesn't work?

Isn't it the basic principle of binary repositories to be organized as a star network where each company is supposed to maintain its own private cache of the upstream CDN?
