### ISSUE TITLE
Click issue in Protractor when using browser.actions() commands in 12.1.5

### ISSUE THREAD

**Issue by HorseJump** [angular/webdriver-manager#399]
Our application uses a canvas element, and in my tests I need to click on objects drawn within the canvas. As I'm sure you're aware, the canvas element does not allow selenium to see what is drawn on it, so we use a hidden div with x,y coordinates to locate what/where to click on. I use browser.actions().mouseMove().perform() and browser.actions().click().perform() for this. Up until I upgraded to 12.1.5 it was working fine. I switched back to 12.1.4 and it's working again. 

There are no errors, it just doesn't click on the objects that it should. I'm using Chrome version 75.0.3770.100 (64 bit) on Windows 10.

**Comment by cnishina** [comment]
This is probably a deprecation of actions() from the browser driver. Since they are probably moving to W3C compatibility this is probably not an issue with webdriver-manager handling the download of drivers. This could be an issue with Protractor.

Closing this since it does not change the downloading of binaries.
