### ISSUE TITLE
Couldn't download latest 76 chrome driver, even if specify the version explicitly

### ISSUE THREAD

**Issue by Abacist** [angular/webdriver-manager#408]
webdriver-manager version: 12.1.6
introduced by Protractor 5.4.2

The latest ChromeDriver version is 76.0.3809.68 according to https://chromedriver.chromium.org/downloads
It fixed a bug in detecting circular reference in JavaScript objects, which exists in 76.0.3809.25 and 76.0.3809.12.

But webdriver-manager update couldn't download it.

=============================================
Logs:

D:\Test\node_modules\.bin>**webdriver-manager update --versions.chrome 76.0.3809.68**
[15:35:11] I/downloader - curl -oD:\Test\node_modules\protractor\node_modules\webdriver-manager\selenium/**chromedriver_76.0.3809.68.zip** **https://chromedriver.storage.googleapis.com/76.0.3809.12/chromedriver_win32.zip**
[15:35:12] I/update - selenium standalone: file exists D:\Test\node_modules\protractor\node_modules\webdriver-manager\selenium\selenium-server-standalone-3.141.59.jar
[15:35:12] I/update - selenium standalone: selenium-server-standalone-3.141.59.jar up to date
[15:35:12] I/update - chromedriver: unzipping chromedriver_76.0.3809.68.zip
[15:35:13] I/update - geckodriver: file exists D:\Test\node_modules\protractor\node_modules\webdriver-manager\selenium\geckodriver-v0.24.0.zip
[15:35:13] I/update - geckodriver: unzipping geckodriver-v0.24.0.zip
[15:35:13] I/update - geckodriver: geckodriver-v0.24.0.exe up to date

**Comment by Abacist** [comment]
It downloaded the 76.0.3809.12 version driver, and renamed it to 76.0.3809.68 version...

**Comment by abhinaba1080** [comment]
I am also facing the same issue. Internally it reflects downgraded version. 

>chromedriver_76.0.3809.68.exe -v
ChromeDriver 76.0.3809.12 (220b19a666554bdcac56dff9ffd44c300842c933-refs/branch-heads/3809@{#83})

**Comment by sk13man** [comment]
Same issue

**Comment by pierre-hilt** [comment]
Hello,
I had a look at the issue and did a fix if you are interested: https://github.com/pierre-hilt/webdriver-manager/commit/f8cb4e237af879882f1f882c0ecbb55af3ec7125

On the logic to get the right chromedriver to download, the patch version was removed (because 76.0.3809.68 is not a valid semver), and so 76.0.3809(.12) is equal to 76.0.3809(.68).

**Comment by sergss** [comment]
please try to reinstall protractor 5.4.2:
```
npm install protractor@5.4.2 --save
```

**Comment by cnishina** [comment]
This unfortunately has to do with the logic there to only look at the first 3 numbers for semver for ChromeDriver. We will fix it but probably not for the legacy branch of webdriver-manager. You could also call `webdriver-manager update --versions.chrome 76.0.3809.68`. 

If you feel like this is something that should be fixed right now, feel free to put in a PR. I'll happily review it. Thanks!

**Comment by VadimSkuratovskyi** [comment]
Hello, 
Faced with the same issue, trying to install chromeDriver --versions.chrome 76.0.3809.68 but downloaded  --versions.chrome 76.0.3809.12 (\node_modules\protractor\node_modules\webdriver-manager\selenium/chromedriver_76.0.3809.68.zip https://chromedriver.storage.googleapis.com/76.0.3809.12/chromedriver_win32.zip)
and then when I try to run tests I receiving an error  Failed: javascript error: circular reference which I assume was fixed in the ChromeDriver 76.0.3809.68
Do you have any ideas on how to fix it?

**Comment by abhinaba1080** [comment]
@VadimSkuratovskyi 

quick fix : install chromedriver through npm -  v76.0.0

https://www.npmjs.com/package/chromedriver

**Comment by VadimSkuratovskyi** [comment]
@abhinaba1080 thank you, it's helped, but do you know, is there any fix planned?

**Comment by abhinaba1080** [comment]
I dont have any idea on that. would be nice to have that in near future as
i want my webdriver manager to handle drivers not the npm itself.

**Comment by TravkinAlex** [comment]
A really counter-intuitive error, investigation took quite some time. Would be great to get it fixed ASAP to avoid crutch-y workarounds.

> If you feel like this is something that should be fixed right now, feel free to put in a PR. I'll happily review it.

@pierre-hilt Could you please submit a PR with your fix, if possible?

**Comment by morozserg** [comment]
And when it will be released?

**Comment by TravkinAlex** [comment]
Would be nice for this to get more attention, I'm sure a lot of people ran into this problem after upgrading to Chrome 76.

**Comment by zensarCompass** [comment]
> please try to reinstall protractor 5.4.2:
> 
> ```
> npm install protractor@5.4.2 --save
> ```

It worked for me. After reinstall protractor I used ng e2e and it automatically downloads latest chormedriver 76.#.###.# version

**Comment by GonzaloCabanasYuste** [comment]
> > please try to reinstall protractor 5.4.2:
> > ```
> > npm install protractor@5.4.2 --save
> > ```
> 
> It worked for me. After reinstall protractor I used ng e2e and it automatically downloads latest chormedriver 76.#.###.# version

Worked for me too

**Comment by GonzaloCabanasYuste** [comment]
> > please try to reinstall protractor 5.4.2:
> > ```
> > npm install protractor@5.4.2 --save
> > ```
> 
> It worked for me. After reinstall protractor I used ng e2e and it automatically downloads latest chormedriver 76.#.###.# version

Worked for me too.

**Comment by vaindil** [comment]
Installing `chromedriver` manually didn't fix anything for me, the old version is still used. I had to manually get the `chromedriver` exe, rename it to have the old version number, and replace the one the package downloaded. No other method worked for me.

**Comment by cnishina** [comment]
Please try 12.1.7. This downloads always the LATEST_RELEASE from chromedriver. This hopefully matches up better with Chrome releases.

If you are having issues with getting the latest:

I would make sure to clean up node_modules before installing. Potentially the version of webdriver-manager satisfies the protractor version number even though there is a newer version available. So it helps to delete the node_modules folder or doing an npm install -f (to force install).

Also this is fixed with https://github.com/angular/webdriver-manager/commit/64795b753b3d00ad2d1f4ac98c531f9e147f3b3e

**Comment by TravkinAlex** [comment]
While getting the latest chromedriver may have been fixed, the get of specific version discussed here is still an issue. I'll create a separate one and update my PR https://github.com/angular/webdriver-manager/pull/413 .
