### ISSUE TITLE
Downloading wrong version of Chromedriver

### ISSUE THREAD

**Issue by rysiaczek13** [angular/webdriver-manager#472]
Hi, I have one problem. When I'm trying to download the latest chromedriver:
npx webdriver-manager update --gecko=false --standalone=false --versions.chrome=85.0.4183.83
the version which is downloaded is 85.0.4183.38.
Do you have any idea, why it not download the correct version?
I/downloader - curl -oC:\TEST\Sources\Src\TestApps\node_modules\webdriver-manager\selenium/chromedriver_85.0.4183.83.zip https://chromedriver.storage.googleapis.com/85.0.4183.38/chromedriver_win32.zip

**Comment by Tyf0x** [comment]
Does anybody else have this issue? This broke our e2e tests on appveyor.

We're trying to use `webdriver-manager update --versions.chrome $env:CHROME_VERSION --verbose --gecko false` where CHROME_VERSION = 85.0.4183.87

webdriver-manager ends up downloading the version 85.0.4183.**38** instead BUT saving it in a archive named 85.0.4183.**87**.

![image](https://user-images.githubusercontent.com/6980921/91673266-aaa79880-eb76-11ea-8fdd-1dce3c38e454.png)

This then ends up breaking the tests because chromedriver cannot find chrome:
![image](https://user-images.githubusercontent.com/6980921/91673394-43d6af00-eb77-11ea-841b-72f2c72c32df.png)

Which I assume was fixed in build .83:

![image](https://user-images.githubusercontent.com/6980921/91673456-86988700-eb77-11ea-9120-f10fa606ddaa.png)

**Comment by Shanson90** [comment]
We have this issue as well.

**Comment by lotz** [comment]
We are facing this issue too, as `85.0.4183.87` has some fixes to deal with closing alerts that we need. Unfortunately, `webdriver-manager update` uses the _first_ version it can find for `85.0.4183` (which is `.38`), rather than the _last_ version (`.87`). This is happening somewhere in the `getSpecificChromeDriverVersion()` function of `chrome_xml.ts`.

**Comment by Blackbaud-BobbyEarl** [comment]
This bug seems to have been present for quite some based on #424 and #408.  I believe it is only applicable on `win32` systems using an `x64` architecture where multiple versions exist for the same major version.  The reason being [line 103](https://github.com/angular/webdriver-manager/blob/legacy/lib/binaries/chrome_xml.ts#L103).

As we iterate through the (already filtered to the OS) list of possible versions, the code is able to catch the last matching version (with the last `.digits` removed) because those fall in to the successful `else if` branch as `mac64` and `linux64` exist.

I used the red -> green approach with the unit test I added in #473 to show the current bug and potential fix.

**Comment by lotz** [comment]
Has anyone found a reliable way to work around this issue? I've tried downloading the correct version of ChromeDriver directly, and placing it in the correct `node_modules` sub-folder inside the `protractor` dependency, but it just gets overwritten later as Protractor itself updates it pretty late.

Some other options I can think of:

* Patch the affected `chrome_xml.js` file on the fly.
* Start a Selenium server and configure Protractor to use that.

**Comment by lotz** [comment]
Looks like this has been discussed a few times before in https://github.com/angular/webdriver-manager/issues/424 and https://github.com/angular/webdriver-manager/issues/401, and there are a few PRs that have been open for a while (https://github.com/angular/webdriver-manager/pull/413 and https://github.com/angular/webdriver-manager/pull/447).

**Comment by lotz** [comment]
I've worked around this by patching the `chrome_xml.js` file on the fly: https://gist.github.com/lotz/d33f550d48dd125344d62321a8905d8b

To use, just add to your NPM `postinstall` script like so:

    "postinstall": "node ./patch-webdriver-manager.js && webdriver-manager update"
